#!/usr/bin/env bash

script_name=$(echo "$0" | sed -E 's,([^:]+):,/\1,g')
echo "$script_name" dispatching "$1"

# Build the environment if it doesn't already exist. We try to recreate the
# bash environment as if invocated with `--login`.
if [[ "$SHLVL" < 2 ]]; then
    
    # Global profile.
    if [[ -f /etc/profile ]]; then
        source /etc/profile
    fi
    
    # User profile.
    for x in ~/.bash_profile ~/.bash_login ~/.profile; do
        if [[ -f $x ]]; then
            source $x
            break
        fi
    done
fi

# Launch it in the background.
python -m sgactions.dispatch "$1" &

# Disconnect it from this shell.
disown %%